In [1]:
import numpy as np
import pandas as pd
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer
from sklearn import preprocessing

In [23]:
import sys
import sklearn
print(sys.version)
!python --version
print("numpy:",np.__version__)
print("sklearn:",sklearn.__version__)

3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Python 3.9.12
numpy: 1.21.5
sklearn: 1.0.2


# 1.3Ghz

In [79]:
dataset=pd.read_csv("CpuTempDataSet_For_1.3Ghz.csv")
dataset

CPU_LOAD_1000  MEMORY USAGE  PAGE FAULT  CPU IDLE TIME  CACHE MISS  \
0              3.4        12.345          66          8.934        1123   
1              3.4        12.345          67          8.900        1124   
2              3.4        12.345          67          8.300        1125   
3              3.4        12.345          68          7.990        1126   
4              3.4        12.345          68          7.980        1126   
..             ...           ...         ...            ...         ...   
387            7.2        11.378         172          7.030        1133   
388            7.2        11.378         173          7.030        1133   
389            7.2        11.378         174          7.030        1133   
390            7.2        11.378         175          7.030        1133   
391            7.2        11.378         176          7.030        1133   

     TEMPERATURE       LABEL  
0          57.00   58.113546  
1          57.00   58.617419  
2          57.00   58.468332  
3          57.00   57.944083  
4          57.00   57.118212  
..           ...         ...  
387       144.34  146.014278  
388       144.74  145.700933  
389       145.14  147.010833  
390       145.54  147.070817  
391       145.94  147.691754  

[392 rows x 7 columns]

In [80]:
dataset_=dataset.replace('[^\d.]', '',regex=True).astype(float)
dataset_

CPU_LOAD_1000  MEMORY USAGE  PAGE FAULT  CPU IDLE TIME  CACHE MISS  \
0              3.4        12.345        66.0          8.934      1123.0   
1              3.4        12.345        67.0          8.900      1124.0   
2              3.4        12.345        67.0          8.300      1125.0   
3              3.4        12.345        68.0          7.990      1126.0   
4              3.4        12.345        68.0          7.980      1126.0   
..             ...           ...         ...            ...         ...   
387            7.2        11.378       172.0          7.030      1133.0   
388            7.2        11.378       173.0          7.030      1133.0   
389            7.2        11.378       174.0          7.030      1133.0   
390            7.2        11.378       175.0          7.030      1133.0   
391            7.2        11.378       176.0          7.030      1133.0   

     TEMPERATURE       LABEL  
0          57.00   58.113546  
1          57.00   58.617419  
2          57.00   58.468332  
3          57.00   57.944083  
4          57.00   57.118212  
..           ...         ...  
387       144.34  146.014278  
388       144.74  145.700933  
389       145.14  147.010833  
390       145.54  147.070817  
391       145.94  147.691754  

[392 rows x 7 columns]

In [81]:
dataset_.dtypes

CPU_LOAD_1000    float64
MEMORY USAGE     float64
PAGE FAULT       float64
CPU IDLE TIME    float64
CACHE MISS       float64
TEMPERATURE      float64
LABEL            float64
dtype: object

In [82]:
X=dataset.iloc[:,0:6]
y=dataset.iloc[:,6:7]
#dataset.drop('Unnamed: 0', inplace=True, axis=1)

In [84]:
x_unNormilzed =np.array(X)

In [85]:
norsmailzedData = preprocessing.normalize(X)
#norsmilzedData
Data_normalizer=Normalizer(norm='l2').fit(X)
normailizedArray=Data_normalizer.transform(X)
#type(normailizedArray)

In [86]:
print("\nL2 normalized data for 1.3ghz is \n", normailizedArray)


L2 normalized data for 1.3ghz is 
 [[0.00301823 0.01095883 0.05858911 0.00793084 0.99690264 0.05059969]
 [0.0030154  0.01094857 0.05942114 0.00789326 0.99685622 0.05055232]
 [0.00301275 0.01093894 0.0593689  0.00735465 0.99686582 0.05050787]
 ...
 [0.00623088 0.00984652 0.15057959 0.00608376 0.98049814 0.12560415]
 [0.00622979 0.00984481 0.15141861 0.0060827  0.98032735 0.12592837]
 [0.0062287  0.00984308 0.15225721 0.00608164 0.98015581 0.12625237]]


In [87]:
normailizedArray

array([[0.00301823, 0.01095883, 0.05858911, 0.00793084, 0.99690264,
        0.05059969],
       [0.0030154 , 0.01094857, 0.05942114, 0.00789326, 0.99685622,
        0.05055232],
       [0.00301275, 0.01093894, 0.0593689 , 0.00735465, 0.99686582,
        0.05050787],
       ...,
       [0.00623088, 0.00984652, 0.15057959, 0.00608376, 0.98049814,
        0.12560415],
       [0.00622979, 0.00984481, 0.15141861, 0.0060827 , 0.98032735,
        0.12592837],
       [0.0062287 , 0.00984308, 0.15225721, 0.00608164, 0.98015581,
        0.12625237]])

In [88]:
y=np.array(y)
y

array([[ 58.1135463 ],
       [ 58.61741941],
       [ 58.46833224],
       [ 57.94408283],
       [ 57.11821183],
       [ 59.1586028 ],
       [ 57.96314353],
       [ 59.00375833],
       [ 59.45640832],
       [ 58.57057943],
       [ 57.3544982 ],
       [ 58.97261944],
       [ 58.10179937],
       [ 57.10047024],
       [ 59.01491938],
       [ 59.77550775],
       [ 58.11584866],
       [ 59.4065865 ],
       [ 59.38261644],
       [ 58.62770721],
       [ 58.6270751 ],
       [ 60.19665084],
       [ 58.74932259],
       [ 60.21110414],
       [ 60.83421269],
       [ 59.08892848],
       [ 61.20174263],
       [ 60.69045034],
       [ 59.66101034],
       [ 59.97003573],
       [ 61.38614038],
       [ 61.21479503],
       [ 61.54083156],
       [ 61.15898983],
       [ 61.4114064 ],
       [ 61.17410531],
       [ 60.58183018],
       [ 60.89453079],
       [ 60.22561328],
       [ 60.82342394],
       [ 61.76316827],
       [ 62.03133527],
       [ 60.80910403],
       [ 61

In [89]:
df = pd.DataFrame(normailizedArray)

In [90]:
df['y'] = y
print(df)

            0         1         2         3         4         5           y
0    0.003018  0.010959  0.058589  0.007931  0.996903  0.050600   58.113546
1    0.003015  0.010949  0.059421  0.007893  0.996856  0.050552   58.617419
2    0.003013  0.010939  0.059369  0.007355  0.996866  0.050508   58.468332
3    0.003010  0.010929  0.060199  0.007073  0.996821  0.050461   57.944083
4    0.003010  0.010929  0.060199  0.007065  0.996821  0.050461   57.118212
..        ...       ...       ...       ...       ...       ...         ...
387  0.006233  0.009850  0.148900  0.006086  0.980837  0.124955  146.014278
388  0.006232  0.009848  0.149740  0.006085  0.980668  0.125280  145.700933
389  0.006231  0.009847  0.150580  0.006084  0.980498  0.125604  147.010833
390  0.006230  0.009845  0.151419  0.006083  0.980327  0.125928  147.070817
391  0.006229  0.009843  0.152257  0.006082  0.980156  0.126252  147.691754

[392 rows x 7 columns]


In [91]:
pd.DataFrame(df).to_csv('For_1.3Ghz.csv')

## 2Ghz

In [103]:
dataset_2=pd.read_csv("CpuTempDataSet_For_2Ghz.csv")
dataset_2

CPU_LOAD_1000  MEMORY USAGE  PAGE FAULT  CPU IDLE TIME  CACHE MISS  \
0              3.4        12.345          66          8.934        1123   
1              3.4        12.345          67          8.900        1124   
2              3.4        12.345          67          8.300        1125   
3              3.4        12.345          68          7.990        1126   
4              3.4        12.345          68          7.980        1126   
..             ...           ...         ...            ...         ...   
387            7.2        11.378         172          7.030        1133   
388            7.2        11.378         173          7.030        1133   
389            7.2        11.378         174          7.030        1133   
390            7.2        11.378         175          7.030        1133   
391            7.2        11.378         176          7.030        1133   

     TEMPERATURE       LABEL  
0          57.00   58.113546  
1          57.00   58.617419  
2          57.00   58.468332  
3          57.00   57.944083  
4          57.00   57.118212  
..           ...         ...  
387       144.34  146.014278  
388       144.74  145.700933  
389       145.14  147.010833  
390       145.54  147.070817  
391       145.94  147.691754  

[392 rows x 7 columns]

In [104]:
#dataset_2.drop('CPU LOAD', inplace=True, axis=1)
#dataset_2.to_csv("CpuTempDataSet_For_2Ghz.csv",index=False)

In [105]:
x=dataset_2.iloc[:,0:6]
Y=dataset_2.iloc[:,6:7]

In [106]:
x_unNormilzed =np.array(x)

In [107]:
norsmilzedData = preprocessing.normalize(x)
#norsmilzedData
Data_normalizer=Normalizer(norm='l2').fit(x)
NormailizedArray=Data_normalizer.transform(x)
#type(normailizedArray)

In [108]:
print("\nL2 normalized data for 2ghz is \n", NormailizedArray)


L2 normalized data for 2ghz is 
 [[0.00301823 0.01095883 0.05858911 0.00793084 0.99690264 0.05059969]
 [0.0030154  0.01094857 0.05942114 0.00789326 0.99685622 0.05055232]
 [0.00301275 0.01093894 0.0593689  0.00735465 0.99686582 0.05050787]
 ...
 [0.00623088 0.00984652 0.15057959 0.00608376 0.98049814 0.12560415]
 [0.00622979 0.00984481 0.15141861 0.0060827  0.98032735 0.12592837]
 [0.0062287  0.00984308 0.15225721 0.00608164 0.98015581 0.12625237]]


In [109]:
NormailizedArray

array([[0.00301823, 0.01095883, 0.05858911, 0.00793084, 0.99690264,
        0.05059969],
       [0.0030154 , 0.01094857, 0.05942114, 0.00789326, 0.99685622,
        0.05055232],
       [0.00301275, 0.01093894, 0.0593689 , 0.00735465, 0.99686582,
        0.05050787],
       ...,
       [0.00623088, 0.00984652, 0.15057959, 0.00608376, 0.98049814,
        0.12560415],
       [0.00622979, 0.00984481, 0.15141861, 0.0060827 , 0.98032735,
        0.12592837],
       [0.0062287 , 0.00984308, 0.15225721, 0.00608164, 0.98015581,
        0.12625237]])

In [110]:
Y=np.array(Y)
Y

array([[ 58.1135463 ],
       [ 58.61741941],
       [ 58.46833224],
       [ 57.94408283],
       [ 57.11821183],
       [ 59.1586028 ],
       [ 57.96314353],
       [ 59.00375833],
       [ 59.45640832],
       [ 58.57057943],
       [ 57.3544982 ],
       [ 58.97261944],
       [ 58.10179937],
       [ 57.10047024],
       [ 59.01491938],
       [ 59.77550775],
       [ 58.11584866],
       [ 59.4065865 ],
       [ 59.38261644],
       [ 58.62770721],
       [ 58.6270751 ],
       [ 60.19665084],
       [ 58.74932259],
       [ 60.21110414],
       [ 60.83421269],
       [ 59.08892848],
       [ 61.20174263],
       [ 60.69045034],
       [ 59.66101034],
       [ 59.97003573],
       [ 61.38614038],
       [ 61.21479503],
       [ 61.54083156],
       [ 61.15898983],
       [ 61.4114064 ],
       [ 61.17410531],
       [ 60.58183018],
       [ 60.89453079],
       [ 60.22561328],
       [ 60.82342394],
       [ 61.76316827],
       [ 62.03133527],
       [ 60.80910403],
       [ 61

In [111]:
df = pd.DataFrame(NormailizedArray)

In [112]:
df['LABEL'] = Y
print(df)

            0         1         2         3         4         5       LABEL
0    0.003018  0.010959  0.058589  0.007931  0.996903  0.050600   58.113546
1    0.003015  0.010949  0.059421  0.007893  0.996856  0.050552   58.617419
2    0.003013  0.010939  0.059369  0.007355  0.996866  0.050508   58.468332
3    0.003010  0.010929  0.060199  0.007073  0.996821  0.050461   57.944083
4    0.003010  0.010929  0.060199  0.007065  0.996821  0.050461   57.118212
..        ...       ...       ...       ...       ...       ...         ...
387  0.006233  0.009850  0.148900  0.006086  0.980837  0.124955  146.014278
388  0.006232  0.009848  0.149740  0.006085  0.980668  0.125280  145.700933
389  0.006231  0.009847  0.150580  0.006084  0.980498  0.125604  147.010833
390  0.006230  0.009845  0.151419  0.006083  0.980327  0.125928  147.070817
391  0.006229  0.009843  0.152257  0.006082  0.980156  0.126252  147.691754

[392 rows x 7 columns]


In [113]:
pd.DataFrame(df).to_csv('For_2Ghz.csv')